### ISSUE TITLE
Error when throwing splash potions

### ISSUE THREAD

**Issue by robbbak** [cervinakuy/KitPvP#115]
**Description of the bug**
I'm on spigot version 1.8.8 and when throwing a potion i get this error. It doesnt even needs to be thrown on a player.
The potions that I throw come from the kit, I replaced the stew with potions of healing II.
I made the potions in the yml like this:
```
Material: POTION
      Type: SPLASH_POTION
      Effects:
        HEAL:
          Amplifier: 2
          splash: true
```

**Screenshot of /kp debug**
https://prnt.sc/wftb7p

**Additional screenshots or video (if applicable)**

**Pastebin.com of any relevant .yml files (if applicable)**
https://pastebin.com/g2MTzY93
