### ISSUE TITLE
Teleportation after death does not work when 0 seconds before teleportation

### ISSUE THREAD

**Issue by Spinogl** [cervinakuy/KitPvP#237]
**Description of the bug**
When the delay between a player's death and their respawn at the arena reception desk is set to 0, teleportation no longer seems to take place.
Look :

```
Death:
  Title:
    Title: '&c&lDeath!
    Subtitle: '&7Tu vas respawn dans %seconds% secondes.'
    Time: 0 <--- HERE
    Message: '%prefix% &7Reappearance...'
  Sound:
    Sound: AMBIENCE_THUNDER
    Pitch: 1
    Enabled: false
  Commands: []
  Messages:
    Player: '%prefix% &b%victim% &7was shot by &b%killer% &7(&c%killer_health%&7).'
    Shot: '%prefix% &b%victim% &7was shot by &b%killer% &7(&c%killer_health%&7).'
    Fall: '%prefix% &b%victim% &7died from a fall.'
    Void: '%prefix% &b%victim% &7died in a vacuum.
    Fire: '%prefix% &b%victim% &7 died of fire.
    Explosion: '%prefix% &b%victim% &7a explosée.'
    Suicide: '%prefix% &b%victim% &7s''killed himself.'
    Unknown: '%prefix% &b%victim% &7is dead.'
    Enabled: true
Respawn:
  Commands: []
```

Translated with DeepL.com (free version)

**Screenshot of /kp debug**
![image](https://github.com/cervinakuy/KitPvP/assets/28354360/aead19d4-2117-4db2-8dcf-39d299710d99)
