### ISSUE TITLE
Greater custom item support

### ISSUE THREAD

**Issue by bowfun** [cervinakuy/KitPvP#252]
NOTE: This may be more of a bug, but I chose feature request as I have seen other issues with this label that are requesting features included under the scope of this request.

**Description of the feature**
This involves allowing items to have custom properties (such as attributes, NBT, and custom model data) by storing more data. While I know the plugin already has custom abilities, as a developer who works with NBT in my own plugins, I can say it would greatly benefit me to have this method.

**How the feature is useful**
This would allow easier item integration with external plugins (eg. Oraxen), allow for custom textures, and cover the functionality of #136 as well. This may also be able to solve #250 due to this allowing items such as that to be directly integrated into the kit.

**Implementations in other plugins**
An example of a plugin that has a feature like this is [SkyWarsReloaded](https://github.com/lukasvdgaag/SkyWarsReloaded). Here's an example of how it handles my Oraxen item (of course, this could be done in a number of different ways):
```yaml
items:
    - ==: org.bukkit.inventory.ItemStack
      v: 3465
      type: BLUE_ICE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"Frost
          "},{"italic":false,"color":"gray","text":"Grenade"}],"text":""}'
        lore:
        - '{"extra":[{"text":" "}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"Damage
          and slow all players in a 10 block radius."}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"Right
          click to use."}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gray","text":"30
          second cooldown"}],"text":""}'
        - '{"extra":[{"text":" "}],"text":""}'
        - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"gold","text":"Rarity:
          "},{"italic":false,"color":"white","text":"ꐼ"}],"text":""}'
        custom-model-data: 1001
        PublicBukkitValues:
          oraxen:id: frost_grenade
          oraxen:original_name: §bFrost §7Grenade
          oraxen:unstackable: '[B;-127B,-92B,94B,-124B,-15B,79B,65B,124B,-115B,-68B,-110B,14B,43B,-10B,-81B,5B]'
```
