### ISSUE TITLE
Hide-Items-With-No-Permission doesn't work

### ISSUE THREAD

**Issue by Jupiops** [cervinakuy/KitPvP#46]
**Description of the bug**
Just like the Title says: If I set Hide-Items-With-No-Permission to true in menu.yml even with Permission kp.* I just can see the Sample Kit

**Screenshot of /kp debug**
![2020-05-05_17 53 20](https://user-images.githubusercontent.com/16759205/81087422-febcac00-8ef9-11ea-989e-762e047fb1b6.png)

**Additional screenshots or video (if applicable)**
![2020-05-05_17 53 50](https://user-images.githubusercontent.com/16759205/81087455-08deaa80-8efa-11ea-9678-2a013852f3a2.png)

**Pastebin.com of any relevant .yml files (if applicable)**

```
# MENU FILE - This is where the menu can be completely customized.
Menu:
  General:
    Title: Kits
    Hide-Items-With-No-Permission: true
    Size: 54
```
